### ISSUE TITLE
[RFC] Base Components 

### ISSUE THREAD

**Issue by navin-moorthy** [timelessco/chakra-components#1]
## Introduction
I hope everyone has got an idea about what we are going to build with Chakra. As a starter, we will be building some base components from the next app that we are going to build. Later we will improve and evolve our component library.

## List of Base Components
- Box
- Flex
- Button
- Text
- Image
- Icon
- Avatar
- Badge
- Search Input
- Dropdown
- Pagination

## Rules
- Finalize on the components that we are going to build.
- Assign each component and build it on a separate branch.
- Once done create a PR to merge with `development` branch with reviewers.
- Push only the most stable version to `master` branch with reviewers.

## Action Items
List of things to be done,

- [x] Create a react boilerplate #3 **@navin-moorthy**
- [x] Add [commitizen](https://github.com/commitizen/cz-cli) #6 **@navin-moorthy**
- [x] Add [all-contributors](https://github.com/all-contributors/all-contributors) #10 **@navin-moorthy**
- [x] Box component #4 **@govindsingh55**
- [x] Flex component **@govindsingh55**
- [x] Text component #5 **@SamrithaS**
- [ ] Button component **@navin-moorthy**

I will edit the RFC and add further action items with PR number based on our comments.

**Comment by prasanna1211** [comment]
@navin-moorthy  List of components looks fine to me. I feel any of the components in design can be achieved by composing from these set. Can you sort them as per the difficulty so that we can create RFC one by one ?

**Comment by navin-moorthy** [comment]
@prasanna1211 I have made the changes, kindly check.

**Comment by prasanna1211** [comment]
@govindsingh55 and @SamrithaS  Have you verified this ? I would suggest you to confirm if these components are good enough for the start.

**Comment by SamrithaS** [comment]
yes I've verified it and its great

**Comment by prasanna1211** [comment]
@navin-moorthy  I think these four points should be rules rather than the Action Items itself. 

- Finalize on the components that we are going to build.
-  Assign each component and build on a separate branch.
-  Once done create a PR to merge with development branch with reviewers.
-  Push only the most stable version to master branch with reviewers.

**Comment by prasanna1211** [comment]
Also Components should have checkbox rather than action items so that it is easy to identify which ones are completed. Also RFCs associated with it can be edited as and when we create one so that everything can be trackable from here.

**Comment by govindsingh55** [comment]
these components are good to start.

**Comment by navin-moorthy** [comment]
@prasanna1211 Action Items will have the components step by step work instead of changing in the list with introduction.

**Comment by prasanna1211** [comment]
I think it is better to add benchmarking libraries here. I would suggest [PriceLine design system](https://priceline.github.io/design-system/) for its composability, 
[Polaris shopify](https://polaris.shopify.com/components/actions/setting-toggle#navigation) for the storybook

1. So storybook will be the interface where we will be giving a demo of the components.
2. We will create another repo for the example page that we are building and use this repo as the base components. (Through git submodules).

Any other benchmarks are fine too.

**Comment by navin-moorthy** [comment]
I will research on the other benchmark libraries in our free time. Since then we can follow **PriceLine**.
@govindsingh55 @SamrithaS your thoughts on this?

**Comment by prasanna1211** [comment]
@navin-moorthy Yes we can do that in individual component  RFCs.

**Comment by SamrithaS** [comment]
@navin-moorthy  yes, we can follow **PriceLine**

**Comment by govindsingh55** [comment]
@navin-moorthy  **Priceline** is Good.

**Comment by prasanna1211** [comment]
Yes, but a bit old. Dot notation won't be available I think but we can adopt it.

**Comment by prasanna1211** [comment]
@samritha Can you take text before button ? Since text is a dependency for button. @navin-moorthy  can you change the order in the list ?

**Comment by SamrithaS** [comment]
sure, I'll do that

**Comment by navin-moorthy** [comment]
@prasanna1211 shall I work on Button? Since Box and Flex are related @govindsingh55 is working on it, your thoughts on this.

**Comment by prasanna1211** [comment]
upto you people. Box, Flex, Button and Text is our initial set. Do as you wish.

**Comment by prasanna1211** [comment]
If pull request is open for anything mention it in the RFC status. same for merging too.

**Comment by prasanna1211** [comment]
Add more infra: [Commitzen](https://github.com/commitizen/cz-cli), [All contributors](https://github.com/all-contributors/all-contributors)

**Comment by govindsingh55** [comment]
from our component, we will expose Box component which will expose the all prop of chakra Box component, but we also expose the FlexBox component which will have prop like {isVisible, isInline, etc.}

**Comment by prasanna1211** [comment]
Guys Lets wrap this RFC with Button component. We will create a new RFC for the next set of components. @navin-moorthy @govindsingh55

**Comment by navin-moorthy** [comment]
Yeah, we can create new RFC with component centric and explained one.
