### ISSUE TITLE
[RFC] Checkbox Component

### ISSUE THREAD

**Issue by navin-moorthy** [timelessco/chakra-components#16]
# Introduction

We will start writing the basic Checkbox from Chakra UI and start building on this later one by one.

## Checkbox to be built

![image](https://user-images.githubusercontent.com/39694575/77746768-77029880-7043-11ea-9c1d-e6a371fcb733.png)

## Initial Steps

- [x] Created a [checkout branch](https://github.com/timelessco/chakra-components/commits/checkbox) to work on this issue.
- [x] Created a [base component](https://github.com/timelessco/chakra-components/commit/360c1c94d08f975a0aab788a0a75b8208d7f003e) by wrapping the Chakra Component
- [x] Decide the code structure our component based on the [sketch file](https://www.dropbox.com/s/33ugiekz2dpff6l/lineups-dam-final-screens.sketch?dl=0)
- [x] Implement it and raise a PR (#17)

## Props to be exposed

- isDisabled
- onBlur
- onChange
- onFocus
- isChecked
- defaultIsChecked
- variantColor
- id
- name
- value
- size
- isIntermediate
- isFullWidth
- isInvalid

## Code collaboration Flow

- [x] In app/app.js, imported ThemeProvider & Theme from chakra as wrapped them around whole app.
- [x] In app/components, create a folder Checkbox and index.js inside to work on our component.
- [x] Import Checkbox component from Chakra UI with a different name using `as`
- [x] Export our basic Checkbox by only passing the children. [Commited](https://github.com/timelessco/chakra-components/commit/019e835fc38040288f03583662ce5578e702359b) **@navin-moorthy**
- [x] Exposing the props will be done later. [Commited](https://github.com/timelessco/chakra-components/commit/360c1c94d08f975a0aab788a0a75b8208d7f003e) **@navin-moorthy**
- [x] Add app's brand color to theme.js to use in variantColor [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604345285) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/12809cf19f0f86669cc6a046c0c18916ba5c4641) **@SamrithaS** 
- [x] Add Font Family to theme.js change the Text style with the Chakra control box [Detials](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604362162) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/a0c90804a8cdb22af2a91f3ddd33c26489ba2b27) **@navin-moorthy**
- [x] Add the Border Color, Border Width & Border Radius of the Checkbox. [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604825307) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/f326a795878d735a40605fc3a9d32470cbfbc1f0) **@SamrithaS** 
- [x] Add the new Check Icon [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604919076) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/740b37d8447c236fc17c77b6f00abb36279126b6) **@govindsingh55** 
- [x] Decide and add correct Focus & hover styles  [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604831050) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/c0eed70d185d28e81ee3f9361dfa0c161a3c764b) **@navin-moorthy**
- [x] Add isDisabled [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604937253) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/9fb4eb8e1b3362da7507371b177f955b80a4f51f) **@SamrithaS**
- [x] Add onBlur, onChange, onFocus & isChecked [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-604954479) [Commited]() **@navin-moorthy**
- [x] Add defaultIsChecked [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/af21a97298944e8af2c53ba8c602266c7e49b6a6) **@SamrithaS**
- [x] Add id, name & value [Details](https://github.com/timelessco/chakra-components/issues/16#issuecomment-605042896) [Commited](https://github.com/timelessco/chakra-components/pull/17/commits/af21a97298944e8af2c53ba8c602266c7e49b6a6) **@navin-moorthy**
- [x] Add rest of the props
- [ ] Add accessibility styles and learn why we are using it

We will improve the steps based on our discussion. First, we need to begin with coding.
At last, we can add accessibility styles.

**Comment by prasanna1211** [comment]
What are the props that we are going to provide ?

**Comment by navin-moorthy** [comment]
> What are the props that we are going to provide ?

We will eventually provide props, first, let's get started with just wrapping around the Checkbox component and improve step by step.

**Comment by SamrithaS** [comment]
my thoughts on what props could be are:
- color of the checkbox
- icon of the checkbox
- number/names of items that are selected
- onClick / onSelected function
- styles like bg, fontColor, fontSize for selected state and unselected ones

thoughts on this? @prasanna1211 @navin-moorthy @govindsingh55

**Comment by navin-moorthy** [comment]
> my thoughts on what props could be are:
> 
> * color of the checkbox
> * icon of the checkbox
> * number/names of items that are selected
> * onClick / onSelected function
> * styles like bg, fontColor, fontSize for selected state and unselected ones
> 
> thoughts on this? @prasanna1211 @navin-moorthy @govindsingh55

yeah, we will add all these props after deciding on which value all these props will take.

**Comment by prasanna1211** [comment]
@SamrithaS  can you elaborate on 
Color ? Background or border ?
Icon ? icon before (or) after. Also why a checkbox needs an icon ?
Checkbox always has only one state. Selected / not selected. Only checkbox group has selected items.
Difference between onClick and onSelect ?
For style there is something called as styled props for chakra. Can you refer to it ?

**Comment by prasanna1211** [comment]
Existing props are in here: https://chakra-ui.com/checkbox, may be compiling from this becomes easy.

**Comment by navin-moorthy** [comment]
> Existing props are in here: https://chakra-ui.com/checkbox, may be compiling from this becomes easy.

Yeah, I will start off with a new branch and the component to refer and by reviewing it we all can get an idea on what we are going to do with Checkbox.

**Comment by SamrithaS** [comment]
> @SamrithaS can you elaborate on
> Color ? Background or border ?
> Icon ? icon before (or) after. Also why a checkbox needs an icon ?
> Checkbox always has only one state. Selected / not selected. Only checkbox group has selected items.
> Difference between onClick and onSelect ?
> For style there is something called as styled props for chakra. Can you refer to it ?

- by color I meant bg as well as border,
- Icon can be customized right? If we'd want a change in Icon rather than a tick mark
- number/names of items that are selected is a property of checkbox group
- referring to styled props

**Comment by prasanna1211** [comment]
@SamrithaS  you can look into this https://chakra-ui.com/checkbox too. Basically what we are going to do is, for our checkbox component we are going to add few styling and missing functionalities like effects / animations and required props. So that when we render just <Checkbox /> it comes out with a pleasing styles.

**Comment by navin-moorthy** [comment]
@govindsingh55 @SamrithaS Let's first do not expose any prop from our component.
We will discuss and fix the base styles from the sketch file and create the base component.

In the example on above PR, I created a red varient Checkox, which we are going to change to match the app styles.

Any thoughts?

**Comment by SamrithaS** [comment]
> @govindsingh55 @SamrithaS Let's first do not expose any prop from our component.
> We will discuss and fix the base styles from the sketch file and create the base component.
> 
> In the example on above PR, I created a red varient Checkox, which we are going to change to match the app styles.
> 
> Any thoughts?

yes, we can proceed by matching the styles

**Comment by navin-moorthy** [comment]
@govindsingh55 @SamrithaS You can pull [this](https://github.com/timelessco/chakra-components/tree/checkbox) and continue working on this component based on our decisions.
Next thing, we can include 

![image](https://user-images.githubusercontent.com/39694575/77635297-59b4c800-6f78-11ea-8c4b-c441ef449bde.png)

## `variantColor = #31a9d8` to our checkbox.

In order to add the variant color, we need to create our own `colors` object in the name of "brand" in theme.js and import it to our ThemeProvider.

Create a multi color shade to support variantColor prop

```json
import { theme } from '@chakra-ui/core';

export default {
  ...theme,
  colors: {
    ...theme.colors,
    brand: {
      '50': '#8ED0E9',
      '100': '#7BC8E6',
      '200': '#69C0E2',
      '300': '#56B8DF',
      '400': '#43B0DB',
      '500': '#31A9D8',
      '600': '#2D9AC5',
      '700': '#298BB1',
      '800': '#247B9E',
      '900': '#206C8A',
    },
  },
};
```
- Import our own theme in app.js as `import theme from './theme';`
- Add the brand color in our component as `<ChakraCheckbox variantColor="brand">{children}</ChakraCheckbox>`

**Comment by navin-moorthy** [comment]
Anyone can find a way to add `Inter font-family` to our project and since our app requires it.
Also, comment on how you are going to implement it.

**Comment by SamrithaS** [comment]
> @govindsingh55 @SamrithaS You can pull [this](https://github.com/timelessco/chakra-components/tree/checkbox) and continue working on this component based on our decisions.
> Next thing, we can include
> 
> ![image](https://user-images.githubusercontent.com/39694575/77635297-59b4c800-6f78-11ea-8c4b-c441ef449bde.png)
> 
> ## `variantColor = #5D5E5E` to our checkbox.
> In order to add the variant color, we need to create our own `colors` object in the name of "brand" in theme.js and import it to our ThemeProvider.

I'll do it

**Comment by navin-moorthy** [comment]
> Anyone can find a way to add `Inter font-family` to our project and since our app requires it.
> Also, comment on how you are going to implement it.

@govindsingh55 Please take this and let us know your thoughts.

**Comment by navin-moorthy** [comment]
Also we need to find a way to over-write the default checkbox border to match the below style when not checked.

Default chakra style,

Also we need to find a way to over-write the default checkbox border to match the below style when not checked.

Default chakra style,
![image](https://user-images.githubusercontent.com/39694575/77636474-2f640a00-6f7a-11ea-9be5-60f4c6c6c2ad.png)

Our component style,
![image](https://user-images.githubusercontent.com/39694575/77636542-499de800-6f7a-11ea-9639-11e846a8f8e8.png)

Any suggestion?

> > @govindsingh55 @SamrithaS You can pull [this](https://github.com/timelessco/chakra-components/tree/checkbox) and continue working on this component based on our decisions.
> > Next thing, we can include
> > ![image](https://user-images.githubusercontent.com/39694575/77635297-59b4c800-6f78-11ea-8c4b-c441ef449bde.png)
> > ## `variantColor = #5D5E5E` to our checkbox.
> > In order to add the variant color, we need to create our own `colors` object in the name of "brand" in theme.js and import it to our ThemeProvider.
> 
> I'll do it

After doing it, make a commitizen commit and let us know, if you face any problem we will help you out.

**Comment by SamrithaS** [comment]
sure, I'll let you know

**Comment by navin-moorthy** [comment]
> > Anyone can find a way to add `Inter font-family` to our project and since our app requires it.
> > Also, comment on how you are going to implement it.
> 
> @govindsingh55 Please take this and let us know your thoughts.

Since @govindsingh55  is away, I will take this and proceed with this implementation steps.

**Comment by navin-moorthy** [comment]
In order to create our own custom checkbox, we will need to refractor our use of Chakra Checkbox to use [Chakra Control Box](https://chakra-ui.com/controlbox)

- Add [Inter Font link](<link rel="stylesheet" href="https://rsms.me/inter/inter.css" />) to our index.html
- Add below snippet to theme.js to use the Font Family across our app

```json
 fonts: {
    ...theme.fonts,
    heading: `Inter,${theme.fonts.heading}`,
    body: `Inter,${theme.fonts.body}`
  },
```
- Add `<CSSReset />` with `import { ThemeProvider, CSSReset } from '@chakra-ui/core';`
- With the @SamrithaS 's commit, use the same props to create our own control box as below 

All the below typography styles are done best to match our app styles.

```html
<Box lineHeight="14px">
    <label style={{ lineHeight: 'inherit' }}>
      {/* This is the sibling input, it's visually hidden */}
      <VisuallyHidden as="input" type="checkbox" defaultChecked />

      {/* This is the control box with a check icon as children */}
      <ControlBox
        borderWidth="1.5px"
        size="14px"
        rounded="sm"
        _checked={{ bg: 'brand.500', color: 'white', borderColor: 'brand.500' }}
      >
        <Icon name="check" size="10px" />
      </ControlBox>

      {/* You can pass additional text */}
      <Box
        as="span"
        verticalAlign="top"
        ml={3}
        fontFamily="body"
        fontSize="13px"
        fontWeight="medium"
        color="#333536"
        letterSpacing="0.13px"
      >
        {children}
      </Box>
    </label>
  </Box>
``` 

Let me know, if we need to change anything or improve on the above plan.

**Comment by navin-moorthy** [comment]
> Also we need to find a way to over-write the default checkbox border to match the below style when not checked.
> 
> Default chakra style,
> 
> Also we need to find a way to over-write the default checkbox border to match the below style when not checked.
> 
> Default chakra style,
> ![image](https://user-images.githubusercontent.com/39694575/77636474-2f640a00-6f7a-11ea-9be5-60f4c6c6c2ad.png)
> 
> Our component style,
> ![image](https://user-images.githubusercontent.com/39694575/77636542-499de800-6f7a-11ea-9639-11e846a8f8e8.png)
> 
> Any suggestion?

@SamrithaS Look at the [sketch file](https://www.dropbox.com/s/33ugiekz2dpff6l/lineups-dam-final-screens.sketch?dl=0) to find border styles - border color, border width, border radius
Also look at the chakra [Control Box] control box to find a way to change our Checkbox styles like the steps above.

**Comment by SamrithaS** [comment]
working on the border, could you tell me if this colour `#919494` should be fine?

**Comment by navin-moorthy** [comment]
> working on the border, could you tell me if this colour `#919494` should be fine?

Since you don't have sketch, I will say the specifications,

borderColor - #8C8D8E
borderWidth - 1.5px
borderRadius - Not accurate, lets fix at 25% as per sketch

**Comment by SamrithaS** [comment]
> > working on the border, could you tell me if this colour `#919494` should be fine?
> 
> Since you don't have sketch, I will say the specifications,
> 
> borderColor - #8C8D8E
> borderWidth - 1.5px
> borderRadius - Not accurate, lets fix at 25% as per sketch

great, thanks

**Comment by navin-moorthy** [comment]
@govindsingh55 Kindly work implementation step for adding check icon from our [sketch file](https://www.dropbox.com/s/33ugiekz2dpff6l/lineups-dam-final-screens.sketch?dl=0) to our Checkbox using theme.js and change the chakra icon since it is different one.

**Comment by navin-moorthy** [comment]
After adding the icon, we will finalize the hove, focus & active styles.
Once all the styles are done, we can work on the props one by one based on the difficulty

**Comment by SamrithaS** [comment]
Steps to add the Border styles:

**theme.js** contains:
` checkbox: {
      borderColor: '#8C8D8E',
    },`

and **Checkbox/index.js** contains:
`   <ControlBox
        borderWidth="1.5px"
        size="14px"
        borderColor="checkbox.borderColor"
        rounded="md"
        _checked={{ bg: 'brand.500', color: 'white', borderColor: 'brand.500' }}
      >
        <Icon name="check" size="10px" />
      </ControlBox>`

**Comment by navin-moorthy** [comment]
Based on research, it seems our checkbox doesn't need any active and hover styles.
So we will be only adding the focus styles
`_focus={{ boxShadow: 'outline' }}`

Any thoughts?

**Comment by navin-moorthy** [comment]
Just now noticed in the sketch file, we need to change the ml for our Children Box should be `ml={2}` instead of 3

**Comment by SamrithaS** [comment]
> Just now noticed in the sketch file, we need to change the ml for our Children Box should be `ml={2}` instead of 3

I'll do it

**Comment by navin-moorthy** [comment]
@SamrithaS We can decide on all the props that we are going to expose from our component since @govindsingh55 is now working on adding the Icon.

**Comment by SamrithaS** [comment]
okay, what's your suggestion on the props?

**Comment by navin-moorthy** [comment]
Initial thoughts for checkbox props are,
- onBlur
- onChange
- onFocus
- isChecked
- disabled

**Comment by navin-moorthy** [comment]
Any other props you feel, we can add it to the top description based on your discussion

**Comment by SamrithaS** [comment]
> Any other props you feel, we can add it to the top description based on your discussion

This seems fine, let's start working on it, and add later if we need more

**Comment by navin-moorthy** [comment]
Sure, can you work on adding disabled first and I will say the styles for that.

**Comment by SamrithaS** [comment]
> Sure, can you work on adding disabled first and I will say the styles for that.

sure

**Comment by navin-moorthy** [comment]
Seems there is hover style for our checkbox, I will work on adding it.
![image](https://user-images.githubusercontent.com/39694575/77728773-372bb900-7023-11ea-8cd2-7667bfe3734d.png)

Add Hover styles as 
```jsx
_hover={{
          borderColor: 'brand.500',
          shadow: '0 0 0 2px #31a7d840, inset 0 0 0 2px #31a7d840',
        }}
```

**Comment by navin-moorthy** [comment]
Based on the comment from Sandeep, we are going to change our Inter Font Family from primary one to Google Fonts which is more performant

`<link href="https://fonts.googleapis.com/css?family=Inter:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">`

**Comment by navin-moorthy** [comment]
@govindsingh55 Please add the steps on how you are implementing, so that we all can agree and do the commit. This will be useful for issue reference

**Comment by SamrithaS** [comment]
@navin-moorthy Can you tell me the styles for disabled?

**Comment by navin-moorthy** [comment]
@SamrithaS the disable state - borderColor: "#E7E8E9" fontColor: "#CACBCC"

**Comment by navin-moorthy** [comment]
I will proceed to add the Icon only to our checkbox and decide on the props later,

```json

  icons: {
    ...theme.icons,
    customCheck: {
      path: (
        <path
          fill="none"
          fillRule="evenodd"
          stroke="#FFF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="1.5"
          d="M1.5 3.788L3.651 6l5.058-5"
        />
      ),
      viewBox: '0 0 10 7',
    },
  },
```

- Add the name to the checkbox `<Icon name="customCheck" size="10px" />`

We can add the props after deciding.

**Comment by navin-moorthy** [comment]
I have listed all props that we are going to expose as per Sandeep's comment

`Make sure we've all the existing props from chakra surfaced.`

We can add additional props anytime.

**Comment by SamrithaS** [comment]
steps for disabled props:

**Homepage/index.js** contains

```
<Box p="4">
        <Checkbox isDisabled>Three</Checkbox>
      </Box>
```

**checkbox/index.js** contains

```
`const Checkbox = ({ children, isDisabled }) => (
  <Box lineHeight="14px">
    <label style={{ lineHeight: 'inherit' }}>
      {/* This is the sibling input, it's visually hidden */}
      <VisuallyHidden as="input" type="checkbox" />

      {/* This is the control box with a check icon as children */}
      <ControlBox
        borderWidth="1.5px"
        size="14px"
        borderColor={isDisabled ? '#E7E8E9' : 'checkbox.borderColor'}
        rounded="md"
        _checked={
          isDisabled
            ? {}
            : { bg: 'brand.500', color: 'white', borderColor: 'brand.500' }
        }
        _focus={{ borderColor: 'outline' }}
        _hover={
          isDisabled
            ? {}
            : {
              borderColor: 'brand.500',
              shadow: '0 0 0 2px #31a7d840, inset 0 0 0 2px #31a7d840',
            }
        }
      >
        <Icon name="customCheck" size="10px" opacity={isDisabled ? 0 : 100} />
      </ControlBox>

      {/* You can pass additional text */}
      <Box
        as="span"
        ml={2}
        fontFamily="body"
        fontSize="13px"
        fontWeight="medium"
        color={isDisabled ? '#CACBCC' : '#333536'}
        letterSpacing="0.13px"
      >
        {children}
      </Box>
    </label>
  </Box>
);

Checkbox.propTypes = {
  children: PropTypes.string,
  isDisabled: PropTypes.bool,
};

export default Checkbox;
`
```

**Comment by govindsingh55** [comment]
> steps for disabled props:
> 
> **Homepage/index.js** contains
> 
> ```
> <Box p="4">
>         <Checkbox isDisabled>Three</Checkbox>
>       </Box>
> ```
> 
> **checkbox/index.js** contains
> 
> ```
> `const Checkbox = ({ children, isDisabled }) => (
>   <Box lineHeight="14px">
>     <label style={{ lineHeight: 'inherit' }}>
>       {/* This is the sibling input, it's visually hidden */}
>       <VisuallyHidden as="input" type="checkbox" />
> 
>       {/* This is the control box with a check icon as children */}
>       <ControlBox
>         borderWidth="1.5px"
>         size="14px"
>         borderColor={isDisabled ? '#E7E8E9' : 'checkbox.borderColor'}
>         rounded="md"
>         _checked={
>           isDisabled
>             ? {}
>             : { bg: 'brand.500', color: 'white', borderColor: 'brand.500' }
>         }
>         _focus={{ borderColor: 'outline' }}
>         _hover={
>           isDisabled
>             ? {}
>             : {
>               borderColor: 'brand.500',
>               shadow: '0 0 0 2px #31a7d840, inset 0 0 0 2px #31a7d840',
>             }
>         }
>       >
>         <Icon name="customCheck" size="10px" opacity={isDisabled ? 0 : 100} />
>       </ControlBox>
> 
>       {/* You can pass additional text */}
>       <Box
>         as="span"
>         ml={2}
>         fontFamily="body"
>         fontSize="13px"
>         fontWeight="medium"
>         color={isDisabled ? '#CACBCC' : '#333536'}
>         letterSpacing="0.13px"
>       >
>         {children}
>       </Box>
>     </label>
>   </Box>
> );
> 
> Checkbox.propTypes = {
>   children: PropTypes.string,
>   isDisabled: PropTypes.bool,
> };
> 
> export default Checkbox;
> `
> ```

style is messing a bit check svg is being visible try to run it

**Comment by navin-moorthy** [comment]
Add the cursor = not allowed when isDisabled

**Comment by navin-moorthy** [comment]
> style is messing a bit check svg is being visible try to run it

For me, everything looks fine, check svg is not visible after passing isDisabled props.
Can you confirm agian.

![image](https://user-images.githubusercontent.com/39694575/77750198-648b5d80-7049-11ea-8a66-7a4f0310c4a2.png)

**Comment by SamrithaS** [comment]
> Add the cursor = not allowed when isDisabled

I'll do it

**Comment by navin-moorthy** [comment]
Doesn't any one get this linting error, while reproducing the above code?

![image](https://user-images.githubusercontent.com/39694575/77750316-8c7ac100-7049-11ea-97e7-be3f1b57472c.png)

Seems to be a conflict between Eslint and Prettier rules.

**Comment by govindsingh55** [comment]
> > style is messing a bit check svg is being visible try to run it
> 
> For me, everything looks fine, check svg is not visible after passing isDisabled props.
> Can you confirm agian.
> 
> ![image](https://user-images.githubusercontent.com/39694575/77750198-648b5d80-7049-11ea-8a66-7a4f0310c4a2.png)

see the white correct tick is bit visible.

on isDisabled = false , add cursor to the <label></label>

**Comment by navin-moorthy** [comment]
@govindsingh55 working on adding any of the props as mentioned in the RFC description?

**Comment by SamrithaS** [comment]
> Doesn't any one get this linting error, while reproducing the above code?
> 
> ![image](https://user-images.githubusercontent.com/39694575/77750316-8c7ac100-7049-11ea-97e7-be3f1b57472c.png)
> 
> Seems to be a conflict between Eslint and Prettier rules.

I'm getting the error, yes it's a conflict

**Comment by govindsingh55** [comment]
purpose of name and value props?

**Comment by navin-moorthy** [comment]
> > Doesn't any one get this linting error, while reproducing the above code?
> > ![image](https://user-images.githubusercontent.com/39694575/77750316-8c7ac100-7049-11ea-97e7-be3f1b57472c.png)
> > Seems to be a conflict between Eslint and Prettier rules.
> 
> I'm getting the error, yes it's a conflict

you can disable the indent for the whole file. Prettier will do the formatting correctly thereafter


> > > style is messing a bit check svg is being visible try to run it
> > 
> > 
> > For me, everything looks fine, check svg is not visible after passing isDisabled props.
> > Can you confirm agian.
> > ![image](https://user-images.githubusercontent.com/39694575/77750198-648b5d80-7049-11ea-8a66-7a4f0310c4a2.png)
> 
> see the white correct tick is bit visible.
> 
> on isDisabled = false , add cursor to the

Great catch, seems even in disable state, checked is working. we need to fix this bug.

![image](https://user-images.githubusercontent.com/39694575/77750828-7de0d980-704a-11ea-9551-6a811b4021d9.png)

**Comment by navin-moorthy** [comment]
> purpose of name and value props?

Since checkbox is an input field, this should need id, name & value props exposed right?

**Comment by navin-moorthy** [comment]
> > > Doesn't any one get this linting error, while reproducing the above code?
> > > ![image](https://user-images.githubusercontent.com/39694575/77750316-8c7ac100-7049-11ea-97e7-be3f1b57472c.png)
> > > Seems to be a conflict between Eslint and Prettier rules.
> > 
> > 
> > I'm getting the error, yes it's a conflict
> 
> you can disable the indent for the whole file. Prettier will do the formatting correctly thereafter
> 
> > > > style is messing a bit check svg is being visible try to run it
> > > 
> > > 
> > > For me, everything looks fine, check svg is not visible after passing isDisabled props.
> > > Can you confirm agian.
> > > ![image](https://user-images.githubusercontent.com/39694575/77750198-648b5d80-7049-11ea-8a66-7a4f0310c4a2.png)
> > 
> > 
> > see the white correct tick is bit visible.
> > on isDisabled = false , add cursor to the
> 
> Great catch, seems even in disable state, checked is working. we need to fix this bug.
> 
> ![image](https://user-images.githubusercontent.com/39694575/77750828-7de0d980-704a-11ea-9551-6a811b4021d9.png)

Found the answer to fix this issue, Thanks @govindsingh55  for pointing out.
@SamrithaS you can add the disabled prop to our input as 

`<VisuallyHidden as="input" type="checkbox" disabled={isDisabled} />`

This is must prop for our input which marks our input to disable and doesn't allow to be checked

**Comment by SamrithaS** [comment]
I tried doing it like this ` <Icon
          name="customCheck"
          size="10px"
          visibility={isDisabled ? 'hidden' : 'visible'}
        />`

Is this fine? The icon is not shown now

**Comment by navin-moorthy** [comment]
> I tried doing it like this ` <Icon name="customCheck" size="10px" visibility={isDisabled ? 'hidden' : 'visible'} />`
> 
> Is this fine?

You can remove visibility, ` <Icon name="customCheck" size="10px" visibility={isDisabled ? 'hidden' : 'visible'} />` and keep it as it is `<Icon name="customCheck" size="10px" />`
and add this 
`<VisuallyHidden as="input" type="checkbox" disabled={isDisabled} />`

Better solution

**Comment by SamrithaS** [comment]
okay

**Comment by navin-moorthy** [comment]
I will add onBlur, onFocus, onChange, isChecked which is simple 😛
Anyone can take add the rest that they are willing to add.

**Comment by navin-moorthy** [comment]
Breif steps to add onBlur, onFocus, onChange & isChecked

- Add them to `input` as

```html
<VisuallyHidden
        as="input"
        type="checkbox"
        disabled={isDisabled}
        checked={isChecked}
        onBlur={onBlur}
        onFocus={onFocus}
        onChange={onChange}
      />
```
- Define the proptypes for each as

```js
  isChecked: PropTypes.bool,
  onBlur: PropTypes.func,
  onFocus: PropTypes.func,
  onChange: PropTypes.func,
```

Also add more examples to try our each seperately

**Comment by govindsingh55** [comment]
- the outermost element need an id. that's right.
- defaultChecked to show initially checked
- value of the input will be isChecked

**Comment by navin-moorthy** [comment]
> * the outermost element need an id. that's right.
> * defaultChecked to show initially checked
> * value of the input will be isChecked

With value prop in frond end they can get the checked value in form.
defaultIsChecked allows us to change the state later.
But if isChecked is given, you cannot change the state, it is hardcoded

**Comment by govindsingh55** [comment]
> > * the outermost element need an id. that's right.
> > * defaultChecked to show initially checked
> > * value of the input will be isChecked
> 
> With value prop in frond end they can get the checked value in form.
> defaultIsChecked allows us to change the state later.
> But if isChecked is given, you cannot change the state, it is hardcoded

isChecked will be passed from the parent component and be controlled from the parent, and onChange this value will be changed at the parent lavel.

**Comment by navin-moorthy** [comment]
> isChecked will be passed from the parent component and be controlled from the parent, and onChange this value will be changed at the parent lavel.

Correct, I did not think in that way. 
But when we don't need to manipulate with isChecked.
exposing value prop will be useful as native HTML value.
We need both to be exposed.
When we need to take control, we can use isChecked otherwise we just can get the values from `value` prop IMO

**Comment by navin-moorthy** [comment]
Updated the description till the last commit 
https://github.com/timelessco/chakra-components/issues/16#issue-588177808

**Comment by SamrithaS** [comment]
steps to add defaultIsChecked prop

- Add it to input as
   `
<VisuallyHidden
        as="input"
        type="checkbox"
        defaultChecked={defaultIsChecked}
      />
`
- Define the proptypes as
` defaultIsChecked: PropTypes.bool,`

**Comment by navin-moorthy** [comment]
I guess everyone is getting the error as shown below in the example

![image](https://user-images.githubusercontent.com/39694575/77757748-c5ba2d80-7057-11ea-95b9-a71d7c7c9974.png)

As said by @govindsingh55 , isChecked should always be used with onChange

I will adjust the example to remove the error.

**Comment by navin-moorthy** [comment]
I am researching on adding the Storybook to our app.
Anyone can add the rest of the props one by one to our checkbox except isIntermediate and isFullWidth will be challenging.
isInvalid prop can be exposed after adding the accessibility styles

**Comment by prasanna1211** [comment]
@navin-moorthy I will add story book before monday. I have an easy way to integrate it.

**Comment by navin-moorthy** [comment]
> @navin-moorthy I will add story book before monday. I have an easy way to integrate it.

Great then, I will continue with the checkbox

**Comment by navin-moorthy** [comment]
Adding id, name, value prop to support native HTML properties to support Form submission

```js
id: PropTypes.string,
name: PropTypes.string,
value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
```

Since value can get string or number, I used oneOfType function for value as shown above

**Comment by navin-moorthy** [comment]
Seems we have black hole inbetween our checkbox icon and string where our cursor disabled is not working.

We can fix that by adding cursor disable to label at the top.

Inorder to add style prop will change the native label to Box as label

**Comment by govindsingh55** [comment]
isIntermediate, isFullWidth, isInvalid, starting working on props.

**Comment by prasanna1211** [comment]
Wait. Don't work on checkbox.

**Comment by prasanna1211** [comment]
1. Managing the layout using 'isFullWidth' should be part of the layout on top of checkbox. Only margin / padding can be applied to checkbox as a position prop.
2. I am not sure about the invalid state of a checkbox. When is the checkbox invalid ?

I can get a sense of errored state and errored style that we need to handle.

**Comment by prasanna1211** [comment]
Please look at this PR: #20 

This shows how I have planned for overriding styles generically for every component.

**Comment by govindsingh55** [comment]
checkbox invalid will make the boder of checkbox red like error state do, not sure about the usecase
isFullWidth will result in width="100%", it can also be handled through the width

**Comment by navin-moorthy** [comment]
> 1. Managing the layout using 'isFullWidth' should be part of the layout on top of checkbox. Only margin / padding can be applied to checkbox as a position prop.
> 2. I am not sure about the invalid state of a checkbox. When is the checkbox invalid ?
> 
> I can get a sense of errored state and errored style that we need to handle.

1 - Sandeep said we need to be exposing Chakra props so that we included `isFullWidth`
2- Checkbox will be invalid when submitting a form - https://www.the-art-of-web.com/html/html5-checkbox-required/ - Can be used to indicate the error state if the user did not accept the terms & conditions while submitting

**Comment by navin-moorthy** [comment]
> checkbox invalid will make the boder of checkbox red like error state do, not sure about the usecase
> isFullWidth will result in width="100%", it can also be handled through the width

Correct. Chakra has already exposed it, why should we need to handle it separately @prasanna1211

**Comment by prasanna1211** [comment]
I think, it is more of how frequently we use it. If we use it frequently then yes we need to. So we can leave it open in the RFC if we skip it for now.

**Comment by govindsingh55** [comment]
> > checkbox invalid will make the boder of checkbox red like error state do, not sure about the usecase
> > isFullWidth will result in width="100%", it can also be handled through the width
> 
> Correct. Chakra has already exposed it, why should we need to handle it separately @prasanna1211

we are not directly using the checkbox in our component but we are trying mimic the chakra checkbox implementation so we have to expose the props that we need

**Comment by navin-moorthy** [comment]
> I think, it is more of how frequently we use it. If we use it frequently then yes we need to. So we can leave it open in the RFC if we skip it for now.

Okay, we will leave it in the RFC. Once the need comes, we can include it.

**Comment by prasanna1211** [comment]
Pending issues to be solved:

- [x] Expose hover, focus, checked style changes as prop that can be customizable
- [x] check icon should be controllable as prop (can be tick or fill or anything)
- [x] Text should always be on the center of the checkbox
- [x] Prop to control the order (Control box and then label (or) label and then control box)
- [x] Double click is creating text highlight
